---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-operator.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "my-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "my-operator.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
        imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
        resources:
          {{- toYaml .Values.operator.resources | nindent 12 }}
