---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polaris-api-server
  labels:
    app: polaris
spec:
  replicas: 2
  selector:
    matchLabels:
      app: polaris
  template:
    metadata:
      labels:
        app: polaris
    spec:
      containers:
      - name: polaris
        image: polaris:tag
        ports:
        - containerPort: 8181
       livenessProbe:
         httpGet:
           path: /q/health
           port: 8182
         initialDelaySeconds: 3
         periodSeconds: 5
       readinessProbe:
         httpGet:
           path: /q/health
           port: 8182
         initialDelaySeconds: 3
         periodSeconds: 5
